version: "3"
services:
  redis:
    image: redis
    ports:
      - "6379:6379"
    volumes:
      - redis:/data

  influxdb:
    image: influxdb
    ports:
      - "8086:8086"
    volumes:
      - influxdb:/var/log
    networks:
      - influxdb
  chronograf:
    image: chronograf
    ports:
      - "8888:8888"
    depends_on:
      - influxdb
    volumes:
      - influxdb:/var/log
    networks:
      - influxdb

volumes:
  influxdb:
  chronograf:
  redis:

networks:
  influxdb:
